site_name: work
site_url: https://vauhoch.zett.cc/work/

nav:
  - Home: index.md
  - Examples: examples.md
  - Release History: releases.md

theme:
  name: material
  icon:
    logo: octicons/command-palette-24
  favicon: static/favicon.png
  palette:
    primary: white
    accent: blue
  features:
    - navigation.tabs
    - toc.integrate

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences

extra:
  pypi-name: work
